### ISSUE TITLE
Point cloud Visualization and shading

### ISSUE THREAD

**Issue by amartiousclem** [luxonis/depthai-unity#30]
Hello, 

I found this repository via [this video on youtube](https://www.youtube.com/watch?v=g-2uEzVfen0&ab_channel=Luxonis)

I'm actually only looking for a way to make a point cloud lit the same way a mesh would. In this video, I noticed that the shadow of the person's arm appears on its chest when it moves. Is this shadow a result of a unity or custom shader, or is it just already in the dynamic point cloud data? If the first suggestion, how did you make this possible?

Also, is there a repo or something where I can find the unity project of the video ?

**Comment by gespona** [comment]
Hi @amartiousclem , sorry for my late reply here. The shadow appears naturally, because when we compute depth from stereo, it's not possible to compute depth from parts camera is not able to see, and it translates to "shadow", but it's part of the point cloud without info. You can find Unity project in this repo under the folder "OAK For Unity/URP"
